---
name: Trigger on pull_request (plan or apply) and labeled (manual) events on GitHub Enterprise self-hosted runner.

on:
  pull_request:
    types: [opened, synchronize, closed, labeled]

jobs:
  tf:
    # Run on usual PR events and when labeled with 'tf-plan'.
    if: ${{ contains(fromJSON('["opened", "synchronize", "closed"]'), github.event.action) || contains(github.event.pull_request.labels.*.name, 'run-plan') || contains(github.event.pull_request.labels.*.name, 'run-apply') }}
    runs-on: self-hosted

    permissions:
      actions: read        # Required to identify workflow run.
      checks: write        # Required to add status summary.
      contents: read       # Required to checkout repository.
      pull-requests: write # Required to add comment and label.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Provision TF
        uses: op5dev/tf-via-pr@v13
        with:
          working-directory: path/to/directory
          command: ${{ github.event.pull_request.merged && 'apply' || 'plan' }}
          arg-lock: ${{ github.event.pull_request.merged }}
          plan-encrypt: ${{ secrets.PASSPHRASE }}
          validate: true
          format: true
        env:
          GH_ENTERPRISE_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}

      - name: Remove label
        if: ${{ contains(github.event.pull_request.labels.*.name, 'run-plan') || contains(github.event.pull_request.labels.*.name, 'run-apply') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          PR_LABEL: ${{ contains(github.event.pull_request.labels.*.name, 'run-plan') && 'run-plan' || 'run-apply' }}
        run: gh api /repos/{owner}/{repo}/issues/${PR_NUMBER}/labels/${PR_LABEL} --method DELETE
