---
name: Test scheduled workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes.

jobs:
  tf:
    runs-on: ubuntu-latest

    permissions:
      actions: read        # Required to identify workflow run.
      checks: write        # Required to add status summary.
      contents: read       # Required to checkout repository.
      issues: write        # Required to open issue.
      pull-requests: write # Required to add PR comment.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup TF
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Plan TF
        id: provision
        uses: op5dev/tf-via-pr@v13
        with:
          working-directory: tests/pass_one
          command: plan
          arg-lock: false
          arg-refresh-only: true
          comment-pr: false

      - name: Open issue on drift
        if: steps.provision.outputs.exitcode != 0
        env:
          GH_TOKEN: ${{ github.token }}
          diff: ${{ steps.provision.outputs.diff }}
          run: ${{ steps.provision.outputs.run-url }}
          result: ${{ steps.provision.outputs.result }}
          summary: ${{ steps.provision.outputs.summary }}
        run: |
          gh api /repos/{owner}/{repo}/issues \
            --method POST \
            --field title="Configuration drift detected" \
            --field body="[View log.]($run)
          <details><summary>Diff of changes.</summary>

          \`\`\`diff
          $diff
          \`\`\`
          </details>
          <details><summary>$summary</summary>

          \`\`\`hcl
          $result
          \`\`\`
          </details>"
