---
name: Test AWS

on:
  pull_request: # Plan.
    paths: [tests/aws/**, .github/workflows/test_aws.yaml]
    types: [opened, synchronize, reopened, labeled]
  merge_group: # Apply.
    types: [checks_requested]

jobs:
  Target:
    runs-on: ubuntu-24.04

    permissions:
      issues: write # Required to add PR label.
      pull-requests: write # Required to add PR comment.

    outputs:
      targets: ${{ steps.changed.outputs.targets }}

    steps:
      - name: Changed files
        id: changed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          # Add link to PR during apply job summary.
          if [[ "${{ github.event_name }}" == "merge_group" ]]; then
            PR_NUMBER=$(echo "${{ github.ref_name }}" | sed -n 's/.*pr-\([0-9]*\)-.*/\1/p')
            echo "View PR [#${PR_NUMBER}](https://github.com/${{ github.repository }}/pull/${PR_NUMBER}) to review planned proposal." >> $GITHUB_STEP_SUMMARY
          fi
          # Remove "tf-plan" PR label if it exists.
          if [[ "${{ github.event.action }}" == "labeled" ]]; then gh api /repos/${{ github.repository }}/issues/${PR_NUMBER}/labels/tf-plan --method DELETE --silent; fi
          # Output changed targets.
          changed=$(gh api /repos/${{ github.repository }}/pulls/${PR_NUMBER}/files --paginate --jq '.[].filename')
          echo "targets=$(echo "$changed" | jq -R 'select(test("^tests/aws/targets/")) | split("/")[3]' | jq -c -s 'unique | sort')" >> $GITHUB_OUTPUT

  TF:
    runs-on: ubuntu-24.04
    needs: [Target]
    if: ${{ needs.Target.outputs.targets != '[]' }}

    permissions:
      actions: read # Required to identify workflow run.
      checks: write # Required to add status summary.
      contents: read # Required to checkout repository.
      id-token: write # Required to authenticate via OIDC.
      issues: write # Required to add PR label.
      pull-requests: write # Required to add PR comment.

    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.Target.outputs.targets) }}

    concurrency:
      cancel-in-progress: false
      group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name}}-${{ matrix.target }}

    environment: ${{ matrix.target }}

    steps:
      - name: Authenticate AWS
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE }}
          role-session-name: tf-via-pr-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Authenticate GitHub
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          # Authenticate with GitHub token.
          git config --global url."https://token:${GH_TOKEN}@github.com".insteadOf "https://github.com"
          # Add the target name as a PR label if it does not exist.
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ !contains(github.event.pull_request.labels.*.name, matrix.target) }}" == "true" ]]; then
            gh api /repos/${{ github.repository }}/issues/${PR_NUMBER}/labels --method POST --field "labels[]=${{ matrix.target }}" --silent
          fi

      - name: Setup Tofu
        uses: opentofu/setup-opentofu@592200bd4b9bbf4772ace78f887668b1aee8f716 # v1.0.5
        with:
          tofu_version: latest
          tofu_wrapper: false

      - name: Checkout PR
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Provision TF
        id: tf
        uses: ./
        with:
          working-directory: tests/aws/targets/${{ matrix.target }}
          command: apply # ${{ github.event_name == 'merge_group' && 'apply' || 'plan' }}
          arg-auto-approve: true
          arg-destroy: true
          arg-lock-timeout: 3m

          plan-encrypt: secrets.TF_ENCRYPTION
          # plan-parity: true
          retention-days: 1

          expand-diff: true
          tag-actor: never
          tool: tofu
